### ISSUE TITLE
ZVT Library

### ISSUE THREAD

**Issue by tinohager** [prosoftgmbh/zvt#3]
Hello we have also developed a ZVT client project that should simplify the tool development. There is also a nuget package for it. You can also receive the receipt through our library. Maybe it could simplify your development. But we don't have support for serial communication yet.

https://github.com/Portalum/Portalum.Zvt

**Comment by jugunter** [comment]
Hi @tinohager, thank you for the information. For now we are happy with the existing solution. We published it because at the time of development there were nearly no information about ZVT available.

All the best, Julian
